### ISSUE TITLE
Keep Enter Steps Box Present Until Done

### ISSUE THREAD

**Issue by brian-menzies** [Orasi/Mustard#13]
I'd love to see the Step Number and Expected Result Box be persistent until the user clicks a "Done" button. Now the user clicks the Create Step Button, the box disappears, the user clicks Add Step, and so on. This upgrade would allow us to quickly enter multiple steps in a more time efficient way.

**Comment by Mattwhooo** [comment]
Sorry, this is more trouble than its worth.  I would have to make major parts of this async and it's not something i'm planning right now
